### ISSUE TITLE
How to use ydiff in "git add -p"?

### ISSUE THREAD

**Issue by bravoecho** [ymattw/ydiff#101]
Hi @ymattw!
Thank you so much for `ydiff` (which I like to pronounce _Yay diff!!!_ :tada:).

I was wondering if there is a way to use it when adding changes interactively with `git add -p`?

Thank you!

**Comment by ymattw** [comment]
Glad you like it. Unfortunately supporting user interaction is not possible.

**Comment by bravoecho** [comment]
No problem, thank you for your prompt reply! 🙂
