### ISSUE TITLE
Request: expose basic diff command as a callable

### ISSUE THREAD

**Issue by ChanceNCounter** [ymattw/ydiff#102]
I realize it's not your intention, but I've been trying for a little while to use ydiff as a dependency for a little CLI app that stores .bak files. It's just *better*! Great little utility here.

But (and I feel pretty dumb needing to ask) I can't seem to figure out what, exactly, I'm supposed to call. Maybe I just haven't spent enough time fooling around. At any rate, I'd very much appreciate (probably with a less generic name)

```
from ydiff import diff

diff(file1, file2)
```

for simplicity.

**Comment by ymattw** [comment]
I am afraid it won't be feasible. The tool is not intended to be used as a library, it's rather a terminal based utility. The majority of the feature is to translate the diff generated by python difflib to colorized strings with ansi sequences.

What's your requirement exactly? If your CLI app is only to diff two files, why not just `diff -u file1 file2 | ydiff`?  Otherwise you probably need to use difflib directly.

**Comment by ChanceNCounter** [comment]
Frankly, I was looking for a drop-in to avoid requiring additional programs, but that might be the solution. Or maybe I just concede that it should be the user's problem...

The function in question is to diff .bakfiles against your current version. Nothing fancy, but the *way* I'm managing .baks is to stick them in your data_home, with timestamps in the filenames, and a tiny sqlite database to make sure we don't lose track of what it's .bak-ing =P

A consequence of that, ofc, is that you can no longer assume a sane filename, so it needs a `bak diff` command. Absent ydiff, I'll probably just stick it in user config and fall back on the system's `diff`.

Thanks anyway! Worth a try.

**Comment by ymattw** [comment]
Version control is exactly for the situation you described ;).

**Comment by ChanceNCounter** [comment]
Yep. For the time being, this thing's naive on purpose. It replaces `cp thing.txt thing.txt.bak` with a few commands, so you stop forgetting those files all over your system. It changes nothing about the actual behavior, which is a straight copy, except that it puts all those files in a single location, with a tiny little db. This way, if the thing fails catastrophically, you can still use the weird filenames to identify the right .bak, and any reset or uninstall script can just wipe the one folder.

VCS is really tempting, but suddenly there are non-code dependencies, and it's much harder for end users to figure out wtf is going on in the event that something kills the database.

The strange decisions we end up making.
