### ISSUE TITLE
Apt package?

### ISSUE THREAD

**Issue by lonix1** [ymattw/ydiff#105]
Is there an APT version, or a PPA? (for debian/ubuntu)

**Comment by ymattw** [comment]
No there is no apt or ppa package.  To be honest I feel packing for one
single file for multiple distributions is a lot of burden.  You can just
install via Python pypi.

**Comment by lonix1** [comment]
You're probably right.

Keep in mind though that the majority of users don't use python. But the majority of linux users do use a debian distribution.
