### ISSUE TITLE
Using "git difftool --extcmd="ydiff" displayes temporary file names

### ISSUE THREAD

**Issue by ideasman42** [ymattw/ydiff#108]
When ydiff is used with `git difftool`it displays the temporary filenames which git creates for the comparison.

Example, 

```
git difftool --no-prompt --extcmd="ydiff --side-by-side --width=120 --color=always --pager=cat" HEAD HEAD~1
```

----

`icdiff` supports this with it's `--is-git-diff` option.

Git uses the environment variables BASE, although I didn't see a convenient way to get the name of the source file when they differ.

This is useful for debugging.
```
git difftool --no-prompt --extcmd="set && echo LOCAL=\$LOCAL REMOTE=\$REMOTE BASE=\$BASE" HEAD HEAD~1
```

**Comment by ymattw** [comment]
`git difftool` generates temp files of the two revisions and sends to external tool for comparison, this is intended behavior.

Run this to verify:

```
git difftool --no-prompt --extcmd="echo" HEAD HEAD~1
```

What you actually need for your use case is `ydiff -s -r HEAD^`.

**Comment by ideasman42** [comment]
Is there a way to use `ydiff` with `git difftool` - not passing the git revisions to ydiff? I need this to support ydiff properly with https://codeberg.org/ideasman42/emacs-diff-ansi

**Comment by ymattw** [comment]
You should be able to pipe the diff to ydiff and send the rendered output back to emacs. You might need to use `--color=always` to bypass the terminal checking in ydiff.
