### ISSUE TITLE
Removed PatchStream breaks other tools that use ydiff as pyhton module

### ISSUE THREAD

**Issue by CyberDem0n** [ymattw/ydiff#117]
I totally understand that from your point of view the API was never publicly documented and therefore removing it doesn't need the major version bump, but could you maybe please make it backward compatible?
I think it will not require a lot of changes, adding something like ``PatchStream  = iter`` seems to be solving it.

Specifically, lack of `PatchStream` breaks Patroni: https://github.com/zalando/patroni/blob/d7454f7bcd8fcea801dcffeb0fd483732c4f4383/patroni/ctl.py#L1926
We can implement the workaround, be remain compatibility between different versions of cdiff/ydiff, but old Patroni versions would still remain broken :(

**Comment by ymattw** [comment]
I never know ydiff is used this way, what a surprise. You are right, `PatchStream = iter` or just `markup_to_pager(buf, opts)` would solve the breakage.

The symbol was removed [long time ago](https://github.com/ymattw/ydiff/commit/ae104bba4314984baea25d9595fc238ee1a1c9da), I would like to avoid undeleting the useless code, if possible.

How is ydiff version defined in your dependency? If a major version bump (e.g `2.0`) fulfills your requirement, I can undelete `PatchStream` and release a `1.3.1` then delete it again in `2.0`.

**Comment by CyberDem0n** [comment]
Hi @ymattw,

Yes, it was removed a long time ago, but today was the first release that includes this commit :)

Unfortunately there is no upper bound in the requirements.txt: https://github.com/zalando/patroni/blob/master/requirements.txt#L13 :(

I am trying avoid pinning versions of dependencies as much as possible to not created dependency hell for users, and unfortunately sometimes it bites us :(
That is, only adding something like `PatchStream = iter` to ydiff and releasing another version will hep.
If you don't want to do it - I would totally understand.
Very sorry for inconvenience.

**Comment by ymattw** [comment]
I see. I think you have to fix the problem either in the ctl.py or the requirements.txt, and ask clients to upgrade. I cannot keep the compatibility in ydiff, sorry. Thanks for your understanding.
