### ISSUE TITLE
Comparison with colordiff in the README

### ISSUE THREAD

**Issue by eyalroz** [ymattw/ydiff#122]
Please add a comparison of your tool with the venerable [colordiff](https://www.[colordiff](https://www.colordiff.org/changes.html).org/changes.html) - which does something very similar - to the README.md file.

**Comment by AloisMahdal** [comment]
It's up to author of course, but... why..?

I understand why someone who already knows colordiff and just found ydiff would want to see such comparison but for that kind of information there are probably better resources to be found, which would not put the burden on ydiff itself.

IMO It's not particularly effective in general either--if someone is exploring options, they might be better off using an independent source such as Wikipedia.  (Individual tools comparing themselves to other seems like a maintenance nightmare.)

**Comment by ymattw** [comment]
They are many other similar tools, each its ups and downs. It would be better to summarize the comparison somewhere else, for example, [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_file_comparison_tools)?

**Comment by ymattw** [comment]
I hope the screenshots quickly explains :)
