### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by Valloric** [ymattw/ydiff#22]
Thanks for creating this project! It's just what I was looking for and it's freaking awesome.

Any chance of getting syntax highlighting for the diff? I'm a big fan of [Meld](http://meldmerge.org/) and it has syntax highlighting, but is overkill to bring up the whole GUI for smaller changes.

This wouldn't have to be complicated or anything; you could use the `mimetypes` module to detect the filetype and then do basic highlighting with [pygments](http://pygments.org/).

Having this feature would make cdiff truly perfect for my needs.

**Comment by albfan** [comment]
Any branch avaliable? The thing is it should use the entire old and new file to render correctly

**Comment by neerajbadlani** [comment]
+1 same problem , what if git diff comes with function context , most of the times when i use git diff i pass function context flag before passing it to ydiff . it may not be able to properly syntax higlight everyething , but language keywords and strings it does at least .
