### ISSUE TITLE
Request a feature like git show

### ISSUE THREAD

**Issue by gitchs** [ymattw/ydiff#46]
Hi, @ymattw. Thanks for your awesome work first.
If I want to view changes by specific commit. I have to run `git show COMMIT_ID`, and **cdiff** only work support something like `git diff` now.
Will you append this feature later?

**Comment by ymattw** [comment]
You can do git show commit-id | cdiff, does this work for you?

**Comment by gitchs** [comment]
@ymattw It works. Thanks for your quick answer.
But it is a workaround method, will you append the feature later?

**Comment by ymattw** [comment]
Maybe later, I am not sure svn and hg has the similar option.  At least you can make a shell alias for the "feature" you want.  If you have a good solution, pull request is very welcome. Thanks.
