### ISSUE TITLE
cdiff command name conflicts with colordiff

### ISSUE THREAD

**Issue by AloisMahdal** [ymattw/ydiff#66]
cdiff is great, I already got pretty much used to it.  Today I was considering making an unofficial RPM package for it.  However. it turns out the `cdiff` binary conflicts with a binary of the same name provided by colordiff package.

What now?  Should we give cdiff an alternate name?

**Comment by ymattw** [comment]
Hi, I guess the name conflict is not a rare case, please just follow whatever existing convention for such case. I am totally ok with an alternate name. BTW cdiff should cover all features of colordiff, you may also consider give colordiff an alternate name :D.

**Comment by AloisMahdal** [comment]
Well, I'm not sure how rare, but I guess not common, since (IMO) it's better to have unique name. It helps promote and support the project (you don't have to clarify you mean *another* cdiff) and helps users who already use *the other cdiff* and would like to install your program.

IOW, the best way seems to be to rename the binary, once and for all, to something that is free in all major distributions.  Also that's what [Fedora packaging guide][1] says.

  [1]: https://fedoraproject.org/wiki/Packaging:Conflicts

I know, it might be too much to ask, but to me it seems better than the other two options: use alternate name and keep explaining and clarifying ad nauseam, or just avoid major distributions.

(And yeah, colordiff's cdiff binary has been in Fedora for at least 12 years (could be more as 12yrs is most I can look up), so I don't think it would be polite to ask *them* to rename it :-))

**Comment by amirouche** [comment]
xdiff is a good name. Like the best diff tool around.

**Comment by AloisMahdal** [comment]
OK, /usr/bin/xdiff seems to be free on Fedora and Debian.  At first search, closest possible confusions seems to be `xxdiff`, which is [a GUI diff tool][1] in Debian, and [a PHP extension][2] called *xdiff*.

 [1]: http://furius.ca/xxdiff/
 [2]: http://php.net/manual/en/intro.xdiff.php

**Comment by AloisMahdal** [comment]
What about `ymdiff` ("@ymattw's diff")?  Search does not bring anything anywhere.

**Comment by gwerbin** [comment]
Yet another reason to change the name: "c-diff" is medical slang for _Clostridium difficile_, a nasty gastrointestinal bacterium. Trust me, you don't want to name your program after _C. difficile_.

**Comment by AloisMahdal** [comment]
Any progress on this?  I know it would be a tough change, but IMO worth it to give this project a unique standing.

(BTW today I discovered git `--word-diff` and it's cool but cdiff/ymdiff still performs better in many cases!)

**Comment by ymattw** [comment]
I tend to use `ydiff` (similar to `diff -y` for side-by-side view). Could you confirm this is still not taken in Fedora package index?

**Comment by ymattw** [comment]
I was stuck at work so took sometime fixing this :P.  Pypi package has been updated, homebrew Formula renaming is pending for review.

**Comment by AloisMahdal** [comment]
OK, I tried looking for:

 *  spec file repo on Fedora (`http://src.fedoraproject.org/rpms/ydiff/`),
 *  *ydiff* bin in Fedora (`dnf provides '*bin/ydiff'`),
 *  *ydiff* package on Debian (web package search and `rmadison ydiff`),
 *  *ydiff* file in Debian (web package search).

No results found for any of these.  I have no idea how to check other distros.

**Comment by AloisMahdal** [comment]
OTOH, simple duckduckgogo search gave me:

 *  https://github.com/bartuer/ydiff
    "a language-aware tool for comparing programs"

 *  https://news.ycombinator.com/item?id=5767664

    5 years old and contains dead link

OT-yet-another-H, `ymdiff` only gives irrelevant results (eg. 'ymdiff'
being typo or some code) and 4th result is this PR! :)

**Comment by ymattw** [comment]
Thanks for the info. I guess it's not possible to find a unique project / binary name yet relevant and meaningful (_ymdiff_ is not meaningful). I am fine with other _ydiff_ projects (pretty dead and not well maintained).  Look like we do not have conflict with `ydiff` on major distros. I've committed the changes anyway ;).

**Comment by ymattw** [comment]
This was fixed in version 1.1.
