### ISSUE TITLE
Will HTML or PDF format file containing the side-by-side diff output support ?

### ISSUE THREAD

**Issue by vegebird** [ymattw/ydiff#69]
cdiff really helps me a lot : )

I prefer the side-by-side output on the screen, and would you like to make it into HTML or PDF format file ? Or do you have any time or plan ?

The result of command "git diff src.c | cdiff -s > src.c.diff" looks like not that shows on the screen, which is side-by-side. If supporting HTML or PDF, it will be better to share and get review from others.

Thanks for your time.

**Comment by ElectricRCAircraftGuy** [comment]
@vegebird , for clarity, you might want to rename the title to: "Please add HTML or PDF output file support, especially for side-by-side diff output"...or something to that effect. Your current wording is hard to understand.

**Comment by ymattw** [comment]
No. Ydiff will remain simple.
