### ISSUE TITLE
Configurable pager behaviour (auto/always/never)

### ISSUE THREAD

**Issue by shaicoleman** [ymattw/ydiff#82]
ydiff currently uses the `--quit-if-one-screen` option of `less`.

Please make the pager behaviour configurable, so the pager can be always enabled or always disabled.

**Comment by ymattw** [comment]
I think the default option passed to less `-FRSX --shift 1` is sensible, curious what's your use case for disabling `-F` / `--quit-if-one-screen`?

**Comment by ymattw** [comment]
I see, some of the use cases do make sense. Unfortunately the default options for `less` were (stolen) from git source code, changing that might break other users. A workaround for you is to reset the `LESS` environment variable (e.g. set to `-R`), either from cmd line or in your script, to override the behavior.

If the workaround is still annoying to you, feel free to send me a pull request. But I would prefer a logic to respect `PAGER` environment variable, rather than introducing new flags (auto/always/never).

**Comment by krader1961** [comment]
@shaicoleman FWIW, I too don't like the default `--quit-if-one-screen` behavior for the reasons you cited. As @ymattw suggests I get my preferred behavior by having a comprehensive `LESS` env var:

```
--HILITE-UNREAD --LONG-PROMPT --RAW-CONTROL-CHARS --chop-long-lines --ignore-case --jump-target=4 --no-init --quiet --search-skip-screen --shift=0 --squeeze-blank-lines --window=-2 --shift=.3 --prompt==%f\$ --prompt=M?f%f:*stdin*.  F %i/%m  .?ltL %lt-%lb/%L:?pt%pt\%:?btByte %bt:-...  C %c  ?Pt%Pt:?pt%pt:\?\?..\%?e EOF.\$
```

For the infrequent times that I don't want a pager I also don't want a side-by-side diffs so I just use `git diff`.  It's not clear to me that a "don't pipe through a pager" option would be useful enough to justify even a few lines of additional code.

**Comment by shaicoleman** [comment]
@krader1961, thanks, setting the LESS variable fixes it for my needs

**Comment by jesseduffield** [comment]
@ymattw I'm adding support for custom pagers to lazygit ([examples](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md)) and I've got a use case for a `--paging=never` flag. I don't want ydiff using less at all, and I'm not aware of any way to make less unconditionally just render to stdout and exit. Happy to put up a PR

**Comment by jesseduffield** [comment]
Worth noting that `git diff | ydiff -p cat` actually still pipes to less, unlike what the docs say

**Comment by jesseduffield** [comment]
scratch that, if I download ydiff directly it works, but it looks like the pip and homebrew versions aren't up to date with master

**Comment by mscottnelson** [comment]
I ran into the same thing as @jesseduffield while trying to get ydiff hooked up to fzf via https://github.com/bigH/git-fuzzy. Any chance we can get a version bump?

**Comment by mscottnelson** [comment]
I'm having trouble making this feasible: pipe side-by-side and colorized output to another process (in this case, fzf preview). Mostly because there doesn't appear to be a way to bypass pipe-detection

**Comment by mamanunu** [comment]
Hello,
I am using `ydif`f as :` ydiff -w 0 -s -p less`, however the `less` page does not have colors. It appears has: 
```
ESC[36mOnly in FolderA
ESC[0mESC[33mESC[0mESC[33mESC[0m
```
If I pass `-p cat` it works fine, but I would like to have one page per file. 
Is it possible to make less interpret the colors?

**Comment by mamanunu** [comment]
> Hello,
> I am using `ydiff` as :` ydiff -w 0 -s -p less`, however the `less` page does not have colors. It appears has:
> 
> ```
> ESC[36mOnly in FolderA
> ESC[0mESC[33mESC[0mESC[33mESC[0m
> ```
> 
> If I pass `-p cat` it works fine, but I would like to have one page per file.
> Is it possible to make less interpret the colors?

This was solved with `-p less -o '-R'`. Sorry for the inconvenience!

**Comment by ymattw** [comment]
-p overrides the default pager (less) and also the default option for it,
just drop `-p less`, it should work.
