### ISSUE TITLE
configure default to side by side

### ISSUE THREAD

**Issue by goldylucks** [ymattw/ydiff#84]
This tool is amazing!!

Is there an option to configure `-s` as default?

So I won't have to do `ydiff -s` every time. I know I can alias it in my shell, but I prefer to have all the logic contained in the program I'm using.

Maybe an option to add `default=true`  directly in the file itself, something like ...

```py
832     parser.add_option(
833         '-s', '--side-by-side', action='store_true', default=true
```

**Comment by ymattw** [comment]
I regretted not making -s default in the beginning, but changing default
behavior is not a good idea. What you can do is either use a shell alias or
export your preferred options into shell environment variable CDIFF_OPTIONS.

**Comment by goldylucks** [comment]
so ... how do I do this?

`export CDIFF_OPTIONS=-s` ? that doesn't seem right :)

**Comment by krader1961** [comment]
@goldylucks This is what I use: ` export YDIFF_OPTIONS=`-s -w0 --wrap -D'`

**Comment by ymattw** [comment]
Yes should be YDIFF_OPTIONS, it's mentioned in the README file, thank you
@krader1961.
